const COMMAND_WORKFLOW_PHASE_MAP: Record<string, string> = Object.freeze({
  'build-fix': 'Build Fixers',
  'cpp-build': 'Build Fixers',
  'flutter-build': 'Build Fixers',
  'gan-build': 'Build Fixers',
  'go-build': 'Build Fixers',
  'gradle-build': 'Build Fixers',
  'kotlin-build': 'Build Fixers',
  'rust-build': 'Build Fixers',
  'code-review': 'Code Review',
  'cpp-review': 'Code Review',
  eval: 'Code Review',
  'flutter-review': 'Code Review',
  'go-review': 'Code Review',
  'kotlin-review': 'Code Review',
  'python-review': 'Code Review',
  'quality-gate': 'Code Review',
  'review-pr': 'Code Review',
  'rust-review': 'Code Review',
  security: 'Code Review',
  'database-migration': 'Core Workflow',
  'feature-dev': 'Core Workflow',
  'feature-development': 'Core Workflow',
  'prompt-optimize': 'Core Workflow',
  'santa-loop': 'Core Workflow',
  docs: 'Docs & Research',
  'update-codemaps': 'Docs & Research',
  'update-docs': 'Docs & Research',
  evolve: 'Learning & Improvement',
  'instinct-export': 'Learning & Improvement',
  'instinct-status': 'Learning & Improvement',
  learn: 'Learning & Improvement',
  'learn-eval': 'Learning & Improvement',
  promote: 'Learning & Improvement',
  'rules-distill': 'Learning & Improvement',
  'skill-create': 'Learning & Improvement',
  claw: 'Loops & Automation',
  devfleet: 'Loops & Automation',
  'loop-start': 'Loops & Automation',
  'loop-status': 'Loops & Automation',
  'multi-backend': 'Loops & Automation',
  'multi-execute': 'Loops & Automation',
  'multi-frontend': 'Loops & Automation',
  'multi-workflow': 'Loops & Automation',
  orchestrate: 'Loops & Automation',
  'prp-implement': 'Loops & Automation',
  council: 'Planning & Architecture',
  'gan-design': 'Planning & Architecture',
  'hookify-configure': 'Planning & Architecture',
  'hookify-list': 'Planning & Architecture',
  'instinct-import': 'Planning & Architecture',
  'multi-plan': 'Planning & Architecture',
  plan: 'Planning & Architecture',
  'prp-plan': 'Planning & Architecture',
  'prp-prd': 'Planning & Architecture',
  'add-language-rules': 'Project & Infrastructure',
  'auto-update': 'Project & Infrastructure',
  'harness-audit': 'Project & Infrastructure',
  jira: 'Project & Infrastructure',
  pm2: 'Project & Infrastructure',
  projects: 'Project & Infrastructure',
  'setup-pm': 'Project & Infrastructure',
  'refactor-clean': 'Refactoring & Cleanup',
  aside: 'Session Management',
  checkpoint: 'Session Management',
  'context-budget': 'Session Management',
  hookify: 'Session Management',
  'hookify-help': 'Session Management',
  'model-route': 'Session Management',
  'prp-commit': 'Session Management',
  'prp-pr': 'Session Management',
  prune: 'Session Management',
  'resume-session': 'Session Management',
  'save-session': 'Session Management',
  sessions: 'Session Management',
  'skill-health': 'Session Management',
  'cpp-test': 'Testing',
  e2e: 'Testing',
  'flutter-test': 'Testing',
  'go-test': 'Testing',
  'kotlin-test': 'Testing',
  'rust-test': 'Testing',
  tdd: 'Testing',
  'test-coverage': 'Testing',
  verify: 'Testing',
});

export function getWorkflowPhaseForCommand(commandName: string): string | undefined {
  const normalized = commandName.startsWith('/') ? commandName.slice(1) : commandName;
  if (normalized.startsWith('commands/')) {
    return undefined;
  }
  return COMMAND_WORKFLOW_PHASE_MAP[normalized];
}

